name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - 'src/infra/*'

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: 'skipComponentGovernanceDetection'
  value: 'false'
- name: 'azureServiceConnection'
  value: 'azure-service-connection'
- group: 'infrastructure-vg'
- group: 'terraform-vg' # Terraform Configuration - tfResourceGroup, tfStorageAccount, tfVersion, tfContainerName and tfKey

stages:

# Deploy Site 1 - Infrastructure and Services
- stage: deployinfra
  displayName: 'Deploy Infrastructure'
  jobs:
  - template: infra.azure.deploy.tpl.yaml
    parameters:
      workingDirectory: 'src/infra'