name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - 'src/infra/*'

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: 'skipComponentGovernanceDetection'
  value: 'false'
- name: 'azureServiceConnection'
  value: 'azure-service-connection'
- group: 'infrastructure-vg'
- group: 'terraform-vg' # Terraform Configuration - tfResourceGroup, tfStorageAccount, tfVersion, tfContainerName and tfKey

stages:

# Deploy, Test and Destroy Infrastructure
- stage: testinfrae2e
  displayName: 'Dev - Deploy Infrastructure E2E'
  variables: 
    destroy: 'false' # destroy after deploy
  jobs:
  - template: infra.azure.deploy.tpl.yaml
    parameters:
      workingDirectory: 'src/infra'
